### ISSUE TITLE
Utilise public CI infrastructure such as travis and appveyor to test builds.

### ISSUE THREAD

**Issue by OmniBlade** [GameProgressive/FullServerBuild#1]
You should set up CI builds to test that the build will succeed on multiple platforms.

**Comment by arves100** [comment]
Hello, thanks for your suggestion. Infortunaly I don't have any CI
infrastructure nor know any public one to use. I'm also not an expert of
this types.
If you know something about this kind of stuff, feel free to suggest.

Il dom 26 ago 2018, 00:46 OmniBlade <notifications@github.com> ha scritto:

**Comment by OmniBlade** [comment]
I'll see if I can come up with configs for appveyor and Travis then.

**Comment by arves100** [comment]
That would be very nice, keep me updated. 💪

Il dom 26 ago 2018, 08:56 OmniBlade <notifications@github.com> ha scritto:

**Comment by arves100** [comment]
Finally travis is now working, I also think appveyor should build right now. Thanks for the contribution.
