### ISSUE TITLE
Commit  7106c60 accidentally included a build directory.

### ISSUE THREAD

**Issue by OmniBlade** [GameProgressive/FullServerBuild#3]
Just FYI that it looks like the last commit accidentally includes a build directory and should probably be removed with a reset, recommit and force push if you want it gone from the commit history.

**Comment by xiaojiuwo1993** [comment]
my bad i try to push the change but i pushed all sorry
________________________________
发件人: OmniBlade <notifications@github.com>
发送时间: 2018年9月22日 22:34
收件人: GameProgressive/GameSpyEmulator
抄送: Subscribed
主题: [GameProgressive/GameSpyEmulator] Commit 7106c60 accidentally included a build directory. (#3)


Just FYI that it looks like the last commit accidentally includes a build directory and should probably be removed with a reset, recommit and force push if you want it gone from the commit history.

―

**Comment by arves100** [comment]
I was looking for this commit for some days, actually @koujiangheng told me about this issue for days, but I wasn't able to find the time to revert. Btw reverted.
